### ISSUE TITLE
CDF talk at DevOps D-DAY event in France

### ISSUE THREAD

**Issue by smontri** [cdfoundation/community-ambassador-program#26]
The intent here is to propose a talk to DevOps D-DAY event in Marseille (France) to present the cdF and its projects

Event will take place on Dec, 1st

Link to the event: https://www.2022.devops-dday.com

It is a F2F event, sessions are recorded and made available on their YouTube channel.

**Comment by zestyroxy** [comment]
Can you share the details of the event, when, etc.?

**Comment by bajpaigarima** [comment]
@smontri   good idea - is it F2F or recorded. For recorded talks we discussed to create few talks based on member projects , CI/CD panel discussion and the SIGs

**Comment by smontri** [comment]
@bajpaigarima @zestyroxy sorry for the delay to answer here... the event is on December 1st in Marseille (South of France), and yes this ia a F2F event.
I'll probably also attend with my company, I need to confirm we can still propose a talk. Will do that next Monday as I'm still not sure we'll be sponsoring it or not with Palo Alto Networks.

**Comment by zestyroxy** [comment]
No worries @smontri. Will you be proposing a talk after all?

**Comment by smontri** [comment]
@zestyroxy unfortunately no as the CFP has been closed some time ago already

**Comment by zestyroxy** [comment]
Ah too, bad. Closing this issue then.
